Repository krishmurarka/Codes-Hacktoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#1 added_controller_apis
  userServer/src/main/java/com/exam/Controller/UserController.java
Labels: enhancement, Hacktoberfest

#2 added job_entitty
  userServer/src/main/java/com/exam/model/Job.java
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted, Hacktoberfest2021

#4 added_repository_class
  userServer/src/main/java/com/exam/Repository/JobCategoryRepository.java
  userServer/src/main/java/com/exam/Repository/JobRepository.java
  userServer/src/main/java/com/exam/Repository/StreamRepository.java
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted, Hacktoberfest2021

#7 Create Day_of_the_Programmer.cpp
  Hackerrank/Day_of_the_Programmer.cpp
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted, Hacktoberfest2021

#9 Create Birthday_Cake_Candles.cpp
  Hackerrank/Birthday_Cake_Candles.cpp
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted, Hacktoberfest2021

#8 Add Brain Kerningam Algo
  Hackerrank/brian_kerningam_algo.cpp
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted, Hacktoberfest2021

#10 Min_Element_In_Array.java
  Hackerrank/Min_Element_In_Array.java
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted, Hacktoberfest2021

#14 Create Extra_Long_Factorials.cpp
  Hackerrank/Extra_Long_Factorials.cpp
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted, Hacktoberfest2021
